version: '3'
services:

  fm-admin-br-runner:
    image: atlastechnologiesteam/github-runner:fm-admin-br
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        - GH_REPOSITORY=https://github.com/atlastechnol/fm-admin-br
        - GH_RUNNER_TOKEN=ANBSJ44TUI3PXPFX7NHDJ5TBAG7O2
        - GH_RUNNER_LABELS=fm-admin-br \
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped